# Generated by Django 5.1 on 2024-08-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('phone_numbers', models.CharField(max_length=50)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
        ),
    ]
