# Generated by Django 5.1 on 2024-08-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_messagesfromcustomers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email for subscribe',
                'verbose_name_plural': 'Emails for subscribes',
            },
        ),
    ]
