# Generated by Django 5.1 on 2024-08-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_subscribeuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeUser',
        ),
    ]
