# Generated by Django 5.1 on 2024-08-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_description_alter_dish_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort'], 'verbose_name_plural': 'Categories'},
        ),
    ]
